<footer class="page-footer small">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">TratoFeito</h5>
        <p class="grey-text text-lighten-4">Ajude e seja ajudado VAI TER Q AJEITAR</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Autores(a gnt pode colocar email, sla ou nada)</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Arthur</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Lucas</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Wender</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © Coltec-UFMG 2017 
    </div>
  </div>
</footer>