<nav class="navbar navbar-dark bg-dark" >
  <a class="navbar-brand" href="principal.php">DAW Eventos</a>
  <input class="form-control col-6 mr-sm-2" type="text" placeholder="Pesquisar" name="pesquisa">
  <form class="form-group" action="carrinho.php" method="post">

      <button type="submit" class="btn btn-light">Carrinho</button>
  </form>
  <button type="button" class="btn btn-danger">Log Out</button>
</nav>

<nav class="navbar navbar-dark bg-dark" >
  <a class="navbar-brand" href="principal.php">DAW Eventos</a>
  <form class="form-inline my-2 my-lg-0 col-10">
        <input class="form-control col-6 mr-sm-2" type="text" placeholder="Pesquisar" name="pesquisa">
        <input class="form-control mr-sm-2 col-2" type="text" placeholder="Login" name="user">
        <input class="form-control mr-sm-2 col-2" type="password" placeholder="Password" name="pwd">
        <button class="btn btn-warning my-2 my-sm-0" type="submit">Log in</button>
 </form>
</nav>

<nav class="navbar navbar-dark bg-dark" >
  <a class="navbar-brand" href="principal.php">DAW Eventos</a>
  <input class="form-control col-6 mr-sm-2" type="text" placeholder="Pesquisar" name="pesquisa">
  <form class="form-group" action="carrinho.php" method="post">

      <button type="submit" class="btn btn-light">Carrinho</button>
  </form>
  <form class="form-group" action="addEvento.php" method="post">

      <button type="submit" class="btn btn-light">Adicionar Evento</button>
  </form>
  <button type="button" class="btn btn-danger">Log Out</button>
</nav>
