<div id="modal" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cadastro de novo Usuário</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row p-3">
          <h5 class="col-3">Nome completo</h5>
          <input type="text" name="name" class="col-9 form-control">
        </div>
        <div class="row p-3">
          <h5 class="col-3">Login</h5>
          <input type="text" name="login" class="col-9 form-control">
        </div>
        <div class="row p-3">
          <h5 class="col-3">Senha</h5>
          <input type="text" name="password" class="col-9 form-control">
        </div>
        <div class="row p-3">
          <h5 class="col-3">E-mail</h5>
          <input type="text" name="email" class="col-9 form-control">
        </div>
      </div>
      <div class="modal-footer">
        <button type="reset" class="btn btn-warning">Limpar</button>
        <button type="submit" class="btn btn-success">Cadastrar</button>
      </div>
    </div>
  </div>
</div>
