<div class="centerbar col-sm-12 col-md-3 col-lg-3">
    <div class="divisores">
        <h2>Suas notificações:</h2>
        <ul>
            <li>Horário de <a class="linkBranco" href="pgMesa.php">Mesa 1</a> foi alterado</li>
            <li>Jogador _D4rk_S0rc3r3r_ saiu da <a class="linkBranco" href="pgMesa.php">Mesa 3</a></li>
            <li>O mestre Krysvera te convidou para a <a class="linkBranco" href="pgMesa.php">Mesa 4</a></li>
        </ul>
    </div>
</div>